name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: SecPwdMan on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] # macos FFM support only on x64_86
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1.3.5
        with:
          java-version: '24'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Example step using Gradle plugin # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        run: |
          chmod +x gradlew
          ./gradlew nativeCompile
