name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: SecPwdMan on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1.4.1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Setup Visual Studio Build Tools (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: Run all tests and build native image
        run: |
          chmod +x gradlew
          ./gradlew allTests
          ./gradlew nativeCompile --info --stacktrace
        env:
          GRADLE_OPTS: -Djava.io.tmpdir=${{ runner.temp }}
          GRADLE_USER_HOME: ${{ runner.temp }}/.gradle
          JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=${{ runner.temp }}
